name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include: [
            { name: windows_x86, arch: x86 },
            { name: windows_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: setup VC-LTL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget install VC-LTL

    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: configure
      run: xmake f -a ${{ matrix.arch }}

    - name: build
      run: xmake

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: v1.5.1
        tag_name: v1.5.1
        files: |
          build/release/${{ matrix.name }}.zip
#    - name: upload
#      uses: actions/upload-artifact@v3
#      with:
#        name: ${{ matrix.name }}
#        path: build/release


